#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun  1 22:27:57 2020

@author: carlos
"""

import sys
import sys
sys.path.insert(0, '/Users/carlos/Work/TSM_CDT/PhD/reaxff-postprocess')
import os
import numpy as np
import nw_initialiser
import networkx as nx 
import time
def get_networks(bonds_filenames,G0,border_cutoff=0.3,mol_limit=200):
    """
    Parameters
    ----------
    bond_filenames : list of strings 
        list of bond dumps to process as strings _in a sorted list_. This is important
        because one may choose to write different files for different stages of a simulation
        but the postprocess takes some initial conditions into account, so they should be provided
        in the same order as they were produced.
    G0 : nx.Graph()
        the initial graph at step 0, with node attributes, obtained through Networkgen class
    border_cutoff : float
        bond order cutoff to use as criteria for considering to atoms bonded
    bdatafile : string
        path to the MAPS-generated lammps datafile containing the bonds. If None or false, the 
        starting bonds and molecules will be taken from the first timestep of the first 
        bond dump in bonds_filenames

    Returns
    -------
    networks: list of nx.Graph()
        list of graphs at each timestep in the bond dumps with the same node attributes
        as G0 (but no surf-surf bonding)
    tsteps: list of int
        timesteps

    """
    
    print('Cutoff:' +str(border_cutoff))
    
    NumAtoms=len(G0)
    
    
    networks=[]
    tsteps=[]
    for bonds_filename in bonds_filenames:
        print(bonds_filename)
        
        
        DataLines = open(bonds_filename, 'r').readlines()
        
        lnum=0
        while lnum<len(DataLines)-1:
            tstep=int(DataLines[lnum].split()[-1])
            tsteps.append(tstep)
            lnum=lnum+7
            
            G_ts = nx.Graph () #new graph with original attributes for this timestep
            G_ts.add_nodes_from (G0.nodes (data = True))
            
            AtomData={}
            AtomBonds={}
            bonds=[]
            
            timestep_lines=DataLines[lnum:lnum+NumAtoms]
            
            for i in range(NumAtoms):
                line = DataLines[lnum+i].split()
                
                try:
                    numbonds = int(line[2])
                except:
                    print(line)
                    print(lnum+i)
                linedata = tuple(map(float,line[:2*numbonds+4])) # saves atom IDs types num of bonds and bond orders                      
    
                AtomNum = linedata[0]
                
                for bond in range(numbonds):
                    #first 3 digits are index, type, nb, then index of bonded atoms, then molecule of the atom, then bond orders
                    if linedata[int(3+numbonds+1+bond)]>border_cutoff:
                                    bonds.append((AtomNum,linedata[int(3+bond)]))
                
            G_ts.add_edges_from(bonds)
            networks.append(G_ts)
            lnum=lnum+NumAtoms+1   
    return networks,tsteps

def write_bonds(G0,networks,tsteps,attribute,fout='bonds_pp.txt'):
    """
    list_networks

    Parameters
    ----------
    G0: nx.Graph()
        reference starting bonds
    networks : list of graphs
        list of graphs corresponding to a dump file (generated by get_networks)
    tsteps : list of ints
        corresponding timesteps for the graphs
    attribute : str
        node attributes to be used for bond counting. Eg, if 'element', it 
        will count the number of P-O bonds and so on; if 'label', P_1-O_2... 
        other attributes can be added to the nodes to be employed with this function

    Generates a file fout with a header and lines with bonds of each tipe per timestep, eg:
    Timestep	Fe-C1	Fe-C2	Fe-C3	Fe-C4	Fe-O1	Fe-O2	O1-P1 O2-P1	O1-C1	O1-C2	O1-C3	O1-C4	O2-C1	O2-C2	O2-C3	O2-C4
   	4000	0	0	0	0	0	0	0	0	0	0	0	0	0	0

    """
    
    #Get all unique values of the corresponding attribute
    values=set()
    for key, value in nx.get_node_attributes(G0,attribute).items():
        values.add(value)
    values=list(values)
    #bonds will be stored in a dictionary, sort the keys:
    
    header="Timestep"+"\t"
    dict_bonds={} #to store bonds, as 'att1-att2:nbonds'
    for i,val1 in enumerate(values):
        for j,val2 in enumerate(values[i:]):
            key=[val1,val2]
            key.sort()
            key='-'.join(key)
            print(key)
            dict_bonds[key]=np.zeros(len(tsteps))
            header=header+key+"\t"
    header=header+"\n"
    
    bfile=open(fout,'w')
    bfile.write(header)
    
    for i,tstep in enumerate(tsteps):
        network=networks[i]
        bline=str(tstep)+"\t"
        for edge in network.edges:
            atr0=network.nodes[edge[0]][attribute]
            atr1=network.nodes[edge[1]][attribute]
            key=[atr0,atr1]
            key.sort()
            key='-'.join(key)
            dict_bonds[key][i]=dict_bonds[key][i]+1
    
        for key in dict_bonds:
            bline=bline+str(int(dict_bonds[key][i]))+"\t"
        bline=bline+"\n"
        bfile.write(bline)
    
            
            
if __name__ == "__main__":
    start=time.time()
    attribute='label'
    datafile='40xTSBP-2xFe3O4-scv.data'
    starting_bfile='40xTNBP-2xFe3O4-scv-BONDS.data'
    tal=nw_initialiser.Networkgen(datafile,starting_bfile)
    G0=tal.G0
    tinit=time.time()
    print('Initialised in:')
    print(tinit-start)
    #nx.get_node_attributes(G0,attribute)
    molgraphs =list(tal.G0.subgraph(c).copy() for c in nx.connected_components(tal.G0) if len(c)<200) 
    tdraw=time.time()
    print('Drawn in:')
    print(tdraw-tinit)
    nx.draw_networkx(molgraphs[0],with_labels=True,labels=dict(molgraphs[0].nodes(data='label')))        
    bonds_filenames=['bonds_equil_500K-2GPa-10ms-40xTSBP-2xFe3O4.txt','bonds_heat_500K-2GPa-10ms-40xTSBP-2xFe3O4.txt','bonds_comp_500K-2GPa-10ms-40xTSBP-2xFe3O4.txt']  
    networks,tsteps=get_networks(bonds_filenames,tal.G0)      
    tprocess=time.time()
    print('Generated networks in')
    print(tprocess-tdraw)
    write_bonds(G0,networks,tsteps,attribute,fout='blabels_pp.txt')
    twrite=time.time()
    print('Wrote bonds in:')
    print(twrite-tprocess)
    